# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
  extensions:    ["with_toc_data"]

# Permalinks
#permalink:        pretty
permalink:          /:categories/:title/
relative_permalinks: true

# Setup
title:            Mildronize's blog
tagline:          'mildronize-blog'
description:      "สมุดจดบันทึก เรื่องราวต่างๆ ที่น่าสนใจ"
keywords:         [note, computer, programming, script, knowledge, coding, technique, collection, glossary, data, infomation, internet, web]
url:              http://dev.mildronize.com/th/
# for dev
# url:              http://127.0.0.1:4000
baseurl:          /
image_url:        public/images/
comment:          true

author:
  codename:       mildronize
  name:           'Thada Wangthammang'
  profile:        images/my-profile.jpg

paginate:         5

google_analytics_id:  UA-62565035-1
